"""
src/preprocessing/run_drain.py
─────────────────────────────────────────────────────────────────────────────
Pipeline position: Tier 2 preprocessing bridge.
Takes the JSONL splits generated by ingest.py, normalizes them, groups them
chronologically by principal into sessions, and passes them through Drain3.

Why 3-field rendering?
  We render events as: "<eventName> <eventSource> <errorCode>"
  We explicitly DROP entityType here. As analyzed in the dataset diagnostics,
  a 94/6 split of AssumedRole vs IAMUser adds almost zero discriminative power,
  but it doubles the vocabulary size. A smaller, denser vocabulary trains a
  much stronger LSTM.

Data Flow:
  data/processed/synthetic_train.jsonl
    -> normalize_event()
    -> group by principalId, sort by eventTime
    -> DrainParser.fit_transform()
    -> data/processed/train_log_keys.json & models/drain3_state.json

  data/processed/synthetic_val.jsonl
    -> normalize_event()
    -> DrainParser.transform() (read-only!)
    -> data/processed/val_log_keys.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Final

# Ensure project root is on sys.path
_PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from src.preprocessing.normalize import NormalizedEvent, normalize_event
from src.detector.drain_parser import DrainParser

# ── Configurable Paths ─────────────────────────────────────────────────────────
PROCESSED_DIR: Final[Path] = Path(
    os.environ.get("PROCESSED_DIR", str(_PROJECT_ROOT / "data" / "processeded1"))
)
MODELS_DIR: Final[Path] = Path(
    os.environ.get("MODELS_DIR", str(_PROJECT_ROOT / "models1" / "deeplog"))
)

def render_event(ev: NormalizedEvent) -> str:
    """Render normalized event into a string for Drain3 to parse.
    
    Format: "EventName EventSource ErrorCode"
    Example: "GetBucketAcl s3.amazonaws.com AccessDenied"
    Example: "ListBuckets s3.amazonaws.com " (Success has empty error code)
    """
    return f"{ev['eventName']} {ev['eventSource']} {ev['errorCode']}".strip()

def process_file(
    input_path: Path, 
    parser: DrainParser, 
    is_train: bool
) -> tuple[list[list[int]], int]:
    """Read a JSONL split, group by principal, and convert to log-key sequences."""
    if not input_path.exists():
        print(f"Warning: {input_path} not found. Skipping.")
        return [], parser.num_keys

    # Group raw records by principalId
    sessions_raw: dict[str, list[dict]] = defaultdict(list)
    with open(input_path, "r", encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            raw_ev = json.loads(line)
            norm_ev = normalize_event(raw_ev)
            sessions_raw[norm_ev["principalId"]].append(norm_ev)

    # Sort each session chronologically and extract the rendered strings
    ordered_sessions: list[list[str]] = []
    for pid, events in sessions_raw.items():
        events.sort(key=lambda e: e["eventTime"])
        rendered_seq = [render_event(e) for e in events]
        ordered_sessions.append(rendered_seq)

    # Flatten for Drain3 processing
    flat_messages: list[str] = [msg for seq in ordered_sessions for msg in seq]
    
    # Process through Drain3
    if is_train:
        print(f"Fitting Drain3 on {len(flat_messages)} messages from {input_path.name}...")
        flat_keys, _ = parser.fit_transform(flat_messages)
    else:
        print(f"Transforming {len(flat_messages)} messages from {input_path.name}...")
        flat_keys = parser.transform(flat_messages)

    # Unflatten back into per-session integer sequences
    seq_keys: list[list[int]] = []
    idx = 0
    for seq in ordered_sessions:
        seq_len = len(seq)
        seq_keys.append(flat_keys[idx : idx + seq_len])
        idx += seq_len

    return seq_keys, parser.num_keys

def save_keys(output_path: Path, sequences: list[list[int]], num_keys: int) -> None:
    """Save the sequences in the JSON format expected by train_deeplog.py."""
    payload = {
        "sequences": sequences,
        "num_keys": num_keys
    }
    with open(output_path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh)
    print(f"Saved {len(sequences)} sequences -> {output_path}")

def main() -> None:
    parser = argparse.ArgumentParser(description="Run Drain3 on CloudTrail splits")
    parser.add_argument("--mode", choices=["mock", "full"], default="mock")
    args = parser.parse_args()

    print(f"\n{'='*60}")
    print(f" Drain3 Log-Key Extraction — mode={args.mode}")
    print(f"{'='*60}\n")

    drain = DrainParser()

    # 1. Process Train (FITS the model)
    train_input = PROCESSED_DIR / "synthetic_train.jsonl"
    train_output = PROCESSED_DIR / "train_log_keys.json"
    train_seqs, num_keys = process_file(train_input, drain, is_train=True)
    save_keys(train_output, train_seqs, num_keys)

    # Save the fitted Drain3 state so it can be loaded during inference
    drain.save_state(MODELS_DIR / "drain3_state.json")

    # 2. Process Val (TRANSFORMS only - no fitting!)
    val_input = PROCESSED_DIR / "synthetic_val.jsonl"
    val_output = PROCESSED_DIR / "val_log_keys.json"
    val_seqs, _ = process_file(val_input, drain, is_train=False)
    if val_seqs:
        save_keys(val_output, val_seqs, num_keys)

    # 3. Process Reserved (TRANSFORMS only)
    reserved_input = PROCESSED_DIR / "synthetic_reserved.jsonl"
    reserved_output = PROCESSED_DIR / "reserved_log_keys.json"
    reserved_seqs, _ = process_file(reserved_input, drain, is_train=False)
    if reserved_seqs:
        save_keys(reserved_output, reserved_seqs, num_keys)

    print(f"\n[Done] Drain3 Vocabulary Size (num_keys) = {num_keys}")
    print("Ready for Tier 2: python src/models/train_deeplog.py --mode full\n")

if __name__ == "__main__":
    main()